version: "3.8"

services:
  mlflow:
    build:
      context: ./training_pipeline
    container_name: mlflow-server
    ports:
      - '5000:5000'
    volumes:
      - ./training_pipeline/mlruns:/app/mlruns
    networks:
      - mlflow

  model-api:
    build:
      context: ./mlops_model_api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - mlflow

networks:
  mlflow: