version: "3.8"

services:
  mlflow:
    build:
      context: ./training_pipeline
    container_name: mlflow-server
    ports:
      - '5000:5000'
    volumes:
      - ./training_pipeline/mlruns:/app/mlruns
    networks:
      - mlflow

  model-api:
    build:
      context: ./mlops_model_api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - ENABLE_METRICS=true
    depends_on:
      - mlflow
    networks:
      - mlflow

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - mlflow
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mlflow

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=debug
    ports:
      - "3000:3000"
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    networks:
      - mlflow


volumes:
  grafana_storage: {}

networks:
  mlflow: