server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

  - job_name: docker
    static_configs:
    - targets:
        - localhost
      labels:
        job: docker
        __path__: /var/lib/docker/containers/*/*-json.log
        __path__regex__: true

  - job_name: model_api
    static_configs:
      - targets:
          - localhost
        labels:
          job: model_api
          __path__: /var/log/app/*.log

    pipeline_stages:
      - output:
          source: log