global:
  scrape_interval: 5s

  external_labels:
    monitor: 'lab3-monitor'

scrape_configs:
  - job_name: 'fastapi-metrics'
    static_configs:
      - targets: ['api:8000']
        labels:
          group: 'fastapi'
          path: 'metrics'
    metrics_path: /metrics

  - job_name: 'fastapi-sysmetrics'
    static_configs:
      - targets: ['api:8000']
        labels:
          group: 'fastapi'
          path: 'sysmetrics'
    metrics_path: /sysmetrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          group: 'node-exporter'

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow-server:5000']
        labels:
          group: 'mlflow'